<?php

return [
    // Common
    'READ_MORE' => 'Read More',
    'BACK_TO_HOME' => 'Back to Home',
    'GET_STARTED' => 'Get Started',
    'CONTACT_SALES' => 'Contact Sales',
    'DOCUMENTATION' => 'Documentation',
    'LAST_UPDATED' => 'Last Updated',

    // API Docs Page
    'API_TITLE' => 'API Reference & Integrations',
    'API_SUBTITLE' => 'Automate your data annotation and human-in-the-loop workflows by integrating Radiif directly into your ML training pipeline.',
    'API_KEY_SECTION' => 'Authentication',
    'API_KEY_DESC' => 'All API requests must contain your organization token in the Authorization header. You can obtain your API key from the developer settings page in your dashboard.',
    'API_ENDPOINT' => 'Base Endpoint',
    'API_DOCS_NAV_GETTING_STARTED' => 'Getting Started',
    'API_DOCS_NAV_AUTHENTICATION' => 'Authentication',
    'API_DOCS_NAV_CREATE_TASK' => 'Create Task',
    'API_DOCS_NAV_GET_RESULTS' => 'Get Results',
    'API_DOCS_NAV_WEBHOOKS' => 'Webhooks',
    
    'API_CODE_TITLE' => 'Example Request',
    'API_CODE_DESC' => 'Choose your preferred language to see how to programmatically submit an annotation or RLHF evaluation task.',
    
    'API_REQ_PARAMS' => 'Request Parameters',
    'API_RESP_FORMAT' => 'Response Format',
    
    // Security & Compliance Page
    'SEC_TITLE' => 'Enterprise Security & Compliance',
    'SEC_SUBTITLE' => 'Enterprise-grade protection for your sensitive training data. Built in full alignment with the Saudi Personal Data Protection Law (PDPL) and global security best practices.',
    'SEC_TRUST_INDICATORS' => 'Trust & Security Controls',
    'SEC_PDPL_TITLE' => 'Saudi PDPL Compliance',
    'SEC_PDPL_DESC' => 'Our platform processes data within Saudi Arabia. We adhere to local hosting regulations and the PDPL framework, ensuring zero data leakage outside borders.',
    'SEC_NDA_TITLE' => 'B2B Non-Disclosure Agreements (NDAs)',
    'SEC_NDA_DESC' => 'Every task is governed by legally binding B2B NDAs signed digitally. All annotations are performed by vetted professionals under corporate legal structures.',
    'SEC_ENCRYPTION_TITLE' => 'Data Encryption',
    'SEC_ENCRYPTION_DESC' => 'Your datasets are encrypted at rest using AES-256 and in transit using TLS 1.3. We enforce secure access patterns and strict role-based access control (RBAC).',
    'SEC_AUDIT_TITLE' => 'Audit Logs & Traceability',
    'SEC_AUDIT_DESC' => 'Track every action taken on your data. Detailed event logs capture who annotated, reviewed, or exported any data slice, providing complete compliance audits.',
    'SEC_VERIFIED_STAFF_TITLE' => 'Verified Professional Staff',
    'SEC_VERIFIED_STAFF_DESC' => 'We do not crowdsource to anonymous users. Our experts are registered corporate employees verified through official social insurance records.',

    // Services: RLHF
    'RLHF_TITLE' => 'Reinforcement Learning from Human Feedback (RLHF)',
    'RLHF_SUBTITLE' => 'Align your Large Language Models (LLMs) with high-quality preference data generated by verified domain experts.',
    'RLHF_HOW_IT_WORKS' => 'How RLHF Works in Radiif',
    'RLHF_STEP_1_TITLE' => 'Prompt Upload',
    'RLHF_STEP_1_DESC' => 'Upload prompts to evaluate model outputs. Specify the guidelines and target criteria (safety, correctness, helpfulness).',
    'RLHF_STEP_2_TITLE' => 'Expert Comparison',
    'RLHF_STEP_2_DESC' => 'Our network of verified legal, technical, and medical professionals ranks multiple model completions and annotates details.',
    'RLHF_STEP_3_TITLE' => 'Reward Model Dataset',
    'RLHF_STEP_3_DESC' => 'Download structured JSONL preference data ready for direct training of your reward models (RM) and DPO loops.',
    'RLHF_USE_CASE_TITLE' => 'RLHF Use Cases',
    'RLHF_USE_CASE_1' => 'Arabic Language Nuances: Tuning models for local dialects, legal terms, and cultural appropriateness.',
    'RLHF_USE_CASE_2' => 'Code Annotation: Verifying complex software code logic, security flaws, and performance optimizations.',
    'RLHF_USE_CASE_3' => 'Professional Expertise: Specialized feedback from certified doctors, lawyers, and financial analysts.',

    // Services: HITL
    'HITL_TITLE' => 'Human-in-the-Loop Validation (HITL)',
    'HITL_SUBTITLE' => 'Bridge the gap between model predictions and enterprise reliability with real-time expert correction and exception handling.',
    'HITL_DESC' => 'Deploy AI with confidence. By placing a human expert in the loop, you can handle low-confidence predictions, eliminate hallucinations, and continuously improve your production models.',
    'HITL_FEATURES_TITLE' => 'Key Features',
    'HITL_FEAT_1_TITLE' => 'Real-time Exception Handling',
    'HITL_FEAT_1_DESC' => 'Route low-confidence model inferences to human experts to verify or correct before serving to customers.',
    'HITL_FEAT_2_TITLE' => 'Continuous Training Loop',
    'HITL_FEAT_2_DESC' => 'Human corrections are automatically packaged and fed back as training data to retrain and improve your model accuracy over time.',
    'HITL_FEAT_3_TITLE' => 'Quality Assurance Guarantees',
    'HITL_FEAT_3_DESC' => 'Double-blind reviews and consensus verification systems ensure annotations have a 99.8% consensus agreement.',

    // Services: Data Infrastructure
    'INFRA_TITLE' => 'Enterprise Data Infrastructure',
    'INFRA_SUBTITLE' => 'Scalable, secure, and developer-friendly workflows designed to ingest, annotate, and export massive datasets.',
    'INFRA_DESC' => 'Radiif is built for modern machine learning teams. Our robust API-first architecture enables seamless integration with your cloud services, data lakes, and private deployments.',
    'INFRA_FEAT_1_TITLE' => 'High-Throughput Pipelines',
    'INFRA_FEAT_1_DESC' => 'Ingest millions of records through our streaming APIs. Scale your labeling tasks dynamically based on team availability.',
    'INFRA_FEAT_2_TITLE' => 'Custom Labeling Interfaces',
    'INFRA_FEAT_2_DESC' => 'Fully customizable layouts tailored to text classification, conversational evaluation, or structured document extraction.',
    'INFRA_FEAT_3_TITLE' => 'Hybrid Deployment Options',
    'INFRA_FEAT_3_DESC' => 'Deploy Radiif within your own VPC or keep data hosted inside secure local sandboxes for extreme regulatory environments.',
];
