name: Deploy Laravel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 157.173.209.184
          username: u432940830
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002

          script: |
            cd ~/laravel-core
            git pull origin master
            npm ci
            npm run build
            php artisan storage:link
            php artisan optimize
            chmod -R 775 storage bootstrap/cache
            echo "✅ Deployment Complete!"